name: Bow Warfare - Reloaded
version: ${project.version}.${BUILD_NUMBER}
main: it.kytech.bowwarfare.BowWarfare
authors: [Double0negative, Hitech95, YoshiGenius]
description: Fully Automated BowWarfare Plugin!

commands:
    bowwarfare:
        description: Bow Warfare Command
        usage: /bw <command> <args>
        aliases: [bowwarfare, bw]

